"use client"

import { useState } from "react"
import { useRouter } from "next/navigation"
import { createClient } from "@/lib/supabase/client"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { AlertCircle, Loader2 } from "lucide-react"

export default function Login() {
    const [email, setEmail] = useState("")
    const [password, setPassword] = useState("")
    const [totpCode, setTotpCode] = useState("")
    const [step, setStep] = useState<"login" | "totp">("login") // 'login' or 'totp'
    const [error, setError] = useState("")
    const [loading, setLoading] = useState(false)

    const router = useRouter()
    const supabase = createClient()

    const handleLogin = async (e: React.FormEvent) => {
        e.preventDefault()
        setLoading(true)
        setError("")

        try {
            const { data, error: signInError } = await supabase.auth.signInWithPassword({
                email,
                password,
            })

            if (signInError) throw signInError

            // Supabase MFA check
            // If the user has MFA enabled, they aren't fully signed in yet.
            // We need to check their AAL (Authenticator Assurance Level)

            const { data: factorsData, error: factorsError } = await supabase.auth.mfa.listFactors()
            if (factorsError) throw factorsError

            // Type assertion to bypass strict typing issues with @supabase/ssr versions varying
            const factorsList = factorsData?.totp || (factorsData as any)?.all || []

            const totpFactor = factorsList.find((f: any) => f.factor_type === 'totp' && f.status === 'verified')

            if (totpFactor) {
                // MFA is required
                setStep("totp")
            } else {
                // No MFA required, or not set up
                router.push("/admin/dashboard")
                router.refresh()
            }
        } catch (err: any) {
            setError(err.message || "Failed to sign in")
        } finally {
            setLoading(false)
        }
    }

    const handleVerifyTotp = async (e: React.FormEvent) => {
        e.preventDefault()
        setLoading(true)
        setError("")

        try {
            const { data: factorsData, error: factorsError } = await supabase.auth.mfa.listFactors()
            if (factorsError) throw factorsError

            const factorsList = factorsData?.totp || (factorsData as any)?.all || []
            const totpFactor = factorsList.find((f: any) => f.factor_type === 'totp' && f.status === 'verified')

            if (!totpFactor) throw new Error("No TOTP factor found")

            const challenge = await supabase.auth.mfa.challenge({ factorId: totpFactor.id })
            if (challenge.error) throw challenge.error

            const verify = await supabase.auth.mfa.verify({
                factorId: totpFactor.id,
                challengeId: challenge.data.id,
                code: totpCode
            })

            if (verify.error) throw verify.error

            // Successfully verified
            router.push("/admin/dashboard")
            router.refresh()

        } catch (err: any) {
            setError(err.message || "Invalid authentication code")
        } finally {
            setLoading(false)
        }
    }

    return (
        <div className="min-h-screen bg-slate-50 flex flex-col items-center justify-center p-4">
            <div className="w-full max-w-md">

                <div className="text-center mb-8">
                    <h1 className="text-2xl font-bold tracking-tight text-slate-900">Dr. Smith Clinic</h1>
                    <p className="text-slate-500 mt-2">Doctor & Staff Portal</p>
                </div>

                <div className="w-full shadow-lg border border-slate-200 rounded-xl bg-white overflow-hidden">
                    <div className="space-y-1 p-6 pb-6 text-center border-b border-slate-100">
                        <h3 className="text-2xl font-semibold tracking-tight text-slate-900">
                            {step === "login" ? "Sign In" : "Two-Factor Authentication"}
                        </h3>
                        <p className="text-sm text-slate-500">
                            {step === "login"
                                ? "Enter your email and password to access the dashboard"
                                : "Enter the code generated by your authenticator app"}
                        </p>
                    </div>
                    <div className="p-6 pt-6">
                        {error && (
                            <div className="bg-red-50 text-red-700 p-3 rounded-md text-sm mb-6 flex items-start border border-red-100">
                                <AlertCircle className="w-4 h-4 mr-2 mt-0.5 flex-shrink-0" />
                                <span>{error}</span>
                            </div>
                        )}

                        {step === "login" ? (
                            <form onSubmit={handleLogin} className="space-y-4">
                                <div className="space-y-2 text-left">
                                    <Label htmlFor="email">Email</Label>
                                    <Input
                                        id="email"
                                        type="email"
                                        placeholder="doctor@clinic.com"
                                        value={email}
                                        onChange={(e) => setEmail(e.target.value)}
                                        required
                                        className="h-11"
                                    />
                                </div>
                                <div className="space-y-2 text-left">
                                    <div className="flex items-center justify-between">
                                        <Label htmlFor="password">Password</Label>
                                    </div>
                                    <Input
                                        id="password"
                                        type="password"
                                        value={password}
                                        onChange={(e) => setPassword(e.target.value)}
                                        required
                                        className="h-11"
                                    />
                                </div>
                                <Button type="submit" className="w-full h-11 mt-2 bg-blue-600 hover:bg-blue-700 font-medium" disabled={loading}>
                                    {loading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}
                                    Sign In
                                </Button>
                            </form>
                        ) : (
                            <form onSubmit={handleVerifyTotp} className="space-y-4">
                                <div className="space-y-2 text-left">
                                    <Label htmlFor="totp">Authentication Code</Label>
                                    <Input
                                        id="totp"
                                        type="text"
                                        inputMode="numeric"
                                        pattern="[0-9]*"
                                        autoComplete="one-time-code"
                                        placeholder="000000"
                                        maxLength={6}
                                        value={totpCode}
                                        onChange={(e) => setTotpCode(e.target.value)}
                                        required
                                        className="h-12 text-center text-lg tracking-widest font-mono"
                                    />
                                </div>
                                <Button type="submit" className="w-full h-11 mt-2 bg-slate-900 hover:bg-slate-800 font-medium" disabled={loading || totpCode.length !== 6}>
                                    {loading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}
                                    Verify Code
                                </Button>
                                <div className="text-center mt-4">
                                    <button
                                        type="button"
                                        onClick={() => setStep("login")}
                                        className="text-sm text-blue-600 hover:underline"
                                    >
                                        Back to login
                                    </button>
                                </div>
                            </form>
                        )}
                    </div>
                </div>

                <p className="text-center text-xs text-slate-500 mt-8">
                    Secure access restricted to authorized clinic personnel only.
                </p>
            </div>
        </div>
    )
}
